version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - nodeapp

  nodeapp:
    image: my-node-app
    container_name: nodeapp
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/usr/src/app
    command: ["node", "server.js"]

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
