create table "public"."card_in_board_opened" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "board_id" bigint,
    "card_number" smallint not null
);


alter table "public"."card_in_board_opened" enable row level security;

CREATE UNIQUE INDEX card_in_board_opened_pkey ON public.card_in_board_opened USING btree (id);

alter table "public"."card_in_board_opened" add constraint "card_in_board_opened_pkey" PRIMARY KEY using index "card_in_board_opened_pkey";

alter table "public"."card_in_board_opened" add constraint "card_in_board_opened_board_id_fkey" FOREIGN KEY (board_id) REFERENCES board(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."card_in_board_opened" validate constraint "card_in_board_opened_board_id_fkey";

grant delete on table "public"."card_in_board_opened" to "anon";

grant insert on table "public"."card_in_board_opened" to "anon";

grant references on table "public"."card_in_board_opened" to "anon";

grant select on table "public"."card_in_board_opened" to "anon";

grant trigger on table "public"."card_in_board_opened" to "anon";

grant truncate on table "public"."card_in_board_opened" to "anon";

grant update on table "public"."card_in_board_opened" to "anon";

grant delete on table "public"."card_in_board_opened" to "authenticated";

grant insert on table "public"."card_in_board_opened" to "authenticated";

grant references on table "public"."card_in_board_opened" to "authenticated";

grant select on table "public"."card_in_board_opened" to "authenticated";

grant trigger on table "public"."card_in_board_opened" to "authenticated";

grant truncate on table "public"."card_in_board_opened" to "authenticated";

grant update on table "public"."card_in_board_opened" to "authenticated";

grant delete on table "public"."card_in_board_opened" to "service_role";

grant insert on table "public"."card_in_board_opened" to "service_role";

grant references on table "public"."card_in_board_opened" to "service_role";

grant select on table "public"."card_in_board_opened" to "service_role";

grant trigger on table "public"."card_in_board_opened" to "service_role";

grant truncate on table "public"."card_in_board_opened" to "service_role";

grant update on table "public"."card_in_board_opened" to "service_role";