name: Deploy SPA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/towers-backend:latest --build-arg ALLOWED_ORIGIN=${{ secrets.ALLOWED_ORIGIN }} --build-arg SUPABASE_PROJECT_ID=${{ secrets.SUPABASE_PROJECT_ID }} --build-arg SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }} --build-arg SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} --build-arg SUPABASE_URL=${{ secrets.SUPABASE_URL }} --build-arg SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/towers-backend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/towers-backend:latest
            cd ~/towers
            docker compose up -d --force-recreate towers-backend